# Generated by Django 4.2.4 on 2023-10-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_newuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='profile_pic',
            field=models.TextField(blank=True),
        ),
    ]
