# Generated by Django 4.2.4 on 2023-11-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_newuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
