# Generated by Django 4.2.4 on 2023-11-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_customuser_created_at_customuser_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=150)),
                ('sex', models.CharField(blank=True, max_length=6)),
                ('civil_status', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=20)),
                ('personal_no', models.CharField(blank=True, max_length=11)),
                ('contact_no', models.CharField(blank=True, max_length=11)),
                ('contact_email', models.CharField(blank=True, max_length=50)),
                ('province', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('house_no', models.CharField(blank=True, max_length=30)),
                ('street_addres', models.CharField(blank=True, max_length=30)),
                ('barangay', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
