# Generated by Django 4.2.4 on 2024-01-09 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_customuser_profile_barangay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=250, null=True)),
                ('action', models.CharField(blank=True, max_length=250, null=True)),
                ('data_entry', models.CharField(blank=True, max_length=250, null=True)),
                ('datetime_acted', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
