# Generated by Django 4.2.4 on 2024-01-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_activity_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_log',
            name='data_entry',
        ),
    ]
