# Generated by Django 4.2.4 on 2024-01-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_activity_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
