# Generated by Django 4.2.4 on 2024-01-24 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Users', '0015_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_group_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('auth_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_group_info', to='auth.group')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_group_info', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_group_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('auth_group',)},
            },
        ),
    ]
