# Generated by Django 5.0.1 on 2024-01-26 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auth_group_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('award_recieved', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('certifying_body', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_faculty', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
