# Generated by Django 5.0.1 on 2024-01-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_faculty_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_certificates',
            name='award_recieved',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_certificates',
            name='certifying_body',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_certificates',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_certificates',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
