<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    </head>
    <body>
        <style>
            img{
                width: 60px !important;
                height: auto !important;
            }
            th, td {
                border: .1rem solid !important;
                border-color: lightgrey !important;
                padding: 10px !important;

            }
            th {
                background-color: #830000 !important;
                color: white !important;
            }
        </style>
        <section class="m-4 p-4">
            <div class="container-fluid">
                <div class="containter-fluid">
                    <div class="content text-center">
                        {{-- <img src="{{ asset('img/pup.png') }}" alt="The Pup Logo - Polytechnic University Of The Philippines Logo@pngkey.com"> </div> --}}
                        <img src="https://www.pngkey.com/png/detail/52-528919_the-pup-logo-polytechnic-university-of-the-philippines.png" alt="The Pup Logo - Polytechnic University Of The Philippines Logo@pngkey.com"> </div>
                    <div class="text-center">
                        <p style="margin: 0 !important;">Republic of the Philippines</p>
                    </div>
                    <div class="container text-center">
                        <h6>Polytechnic University of the Philippines - Quezon City Campus</h6>
                    </div>
                </div>
            </div>
            <div class="mt-4 pt-3 text-center">
                <h5>Faculty Requirement Compliance Report</h5>
                <p style="font-style: italic;">As of
                    @php
                        // 1. Get today's date
                        $todayDate = \Carbon\Carbon::now();

                        echo $todayDate;
                    @endphp
                </p>
            </div>
            <div class="row mt-4">
                <div class="col">Generated By:
                    <b> {{ $user->first_name }} {{ $user->last_name }}
                    </b>
                </div>
                {{-- <div class="col text-end">Date Generated: <b>May 05, 2024 - 3:30PM</b></div> --}}
            </div>
            <div class="container-fluid mt-4 p-4">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Faculty Name</th>
                            <th>Requirement Bin</th>
                            <th>Category</th>
                            <th>Requirement</th>
                            <th>Submission Type</th>
                            <th>Deadline</th>
                            <th>Date Submitted</th>
                            <th>Timeliness</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($datas as $data)
                            <tr>
                                <td>{{ $data->first_name }} {{ $data->last_name }}</td>
                                <td>{{ $data->bin_title }}</td>
                                <td>{{ $data->category }}</td>
                                <td>{{ $data->requirement }}</td>
                                <td>
                                    @if ($data->submission_type)
                                        {{ $data->submission_type }}
                                    @else
                                        For Compliance
                                    @endif
                                </td>

                                <td>{{ $data->bin_deadline }}</td>
                                <td>{{ $data->submission_date == Null ? 'For Compliance': $data->submission_date  }}</td>

                                <td>
                                    @php
                                        // 1. Get today's date
                                        $todayDate = \Carbon\Carbon::now();
                                        $status = $data->status;

                                        // 3. Get deadline date (assuming you have this from your data)
                                        $deadlineDate = \Carbon\Carbon::parse($data->bin_deadline);

                                        $TodayDeadlineDiff = $deadlineDate->diffInDays($todayDate);

                                        if ($data->submission_date){
                                                                                    // 2. Get submission date (assuming you have this from your data)
                                            $submissionDate = \Carbon\Carbon::parse($data->submission_date);
                                            $daysDiff = $deadlineDate->diffInDays($submissionDate);

                                            // Output (you can customize this)
                                            if ($deadlineDate > $submissionDate) {
                                                echo abs($daysDiff+1) . " days ahead of deadline";

                                            } elseif ($daysDiff == 0) {
                                                echo "On time";

                                            } else {

                                                echo abs($daysDiff) . " days late";
                                            }
                                        }

                                        else {

                                            if ($deadlineDate > $todayDate || $TodayDeadlineDiff == 0 && $status == 'Pending' ) {
                                                echo "For Compliance";
                                            }

                                            elseif ($deadlineDate < $todayDate && $status == 'Pending' || $status == 'Approved') {
                                                echo abs($TodayDeadlineDiff) . " days late";
                                            }
                                        }

                                    @endphp
                                </td>

                                <td>
                                    {{ $data->status }}
                                </td>

                            </tr>

                        @endforeach
                    </tbody>
                </table>
            </div>
        </section>
    </body>
</html>








{{-- <!DOCTYPE html>
<html>
    <head>
        <title>Faculty Requirement Compliance Report</title>
        <style>
            /* Basic Styling */
            body { font-family: Arial, sans-serif; }
            table { border-collapse: collapse; width: 100%; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }

            /* Header Styling */
            .header { text-align: center; }
            .header img { float: left; margin-right: 20px; }
            .header-titles h1 { font-weight: normal; }
            .header-titles h2 { font-weight: bold; font-size: 1.2em; }
            .header-titles h3 { font-weight: bold; }

            /* Maroon Color */
            .maroon { background-color: #830000; color: white; }
        </style>


        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    </head>
    <body>

        <div class="header">
            <img src="your_pup_logo.jpg" alt="PUP Logo" height="80">
            <div class="header-titles">
                <h1>Republic of the Philippines</h1>
                <h2>Polytechnic University of the Philippines</h2>
                <h3>Quezon City Branch</h3>
            </div>
        </div>


        <table class="table table-striped"  id="myTable">
            <thead class="pal-1 text-col-2 maroon">
                <tr>
                    <th>Faculty Name</th>
                    <th>Requirement Bin</th>
                    <th>Category</th>
                    <th>Requirement</th>
                    <th>Submission Type</th>
                    <th>Deadline</th>
                    <th>Date Submitted</th>
                    <th>Timeliness</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody id='filtered-bins'>
                @foreach ($datas as $data)
                    <tr>
                        <th scope="row">{{ $data->first_name }} {{ $data->last_name }}</th>
                        <td>{{ $data->bin_title }}</td>
                        <td>{{ $data->category }}</td>
                        <td>{{ $data->requirement }}</td>
                        <td>
                            @if ($data->submission_type)
                                {{ $data->submission_type }}
                            @else
                                <p>For Compliance</p>
                            @endif
                        </td>

                        <td>{{ $data->bin_deadline }}</td>
                        <td>{{ $data->submission_date == Null ? 'For Compliance': $data->submission_date  }}</td>

                        <td>
                            @php
                                // 1. Get today's date
                                $todayDate = \Carbon\Carbon::now();
                                $status = $data->status;

                                // 3. Get deadline date (assuming you have this from your data)
                                $deadlineDate = \Carbon\Carbon::parse($data->bin_deadline);

                                $TodayDeadlineDiff = $deadlineDate->diffInDays($todayDate);

                                if ($data->submission_date){
                                                                            // 2. Get submission date (assuming you have this from your data)
                                    $submissionDate = \Carbon\Carbon::parse($data->submission_date);
                                    $daysDiff = $deadlineDate->diffInDays($submissionDate);

                                    // Output (you can customize this)
                                    if ($deadlineDate > $submissionDate) {
                                        echo abs($daysDiff+1) . " days ahead of deadline";

                                    } elseif ($daysDiff == 0) {
                                        echo "On time";

                                    } else {

                                        echo abs($daysDiff) . " days late";
                                    }
                                }

                                else {

                                    if ($deadlineDate > $todayDate || $TodayDeadlineDiff == 0 && $status == 'Pending' ) {
                                        echo "For Compliance";
                                    }

                                    elseif ($deadlineDate < $todayDate && $status == 'Pending' || $status == 'Approved') {
                                        echo abs($TodayDeadlineDiff) . " days late";
                                    }
                                }

                            @endphp
                        </td>

                        <td class="text-center ">
                            <button type="button"
                                class="  font-medium rounded-full text-sm  px-3 py-1 text-center mr-2 mb-2
                            {{ $data->status == 'Pending' ? 'text-white bg-gray-400' : ($data->status == 'Rejected' ? 'text-white bg-red-500' : ($data->status == 'In review' ? 'text-white bg-blue-500' : 'text-white bg-green-500')) }}
                            ">{{ $data->status }}</button>
                        </td>

                    </tr>

                @endforeach
            </tbody>

        </table>




        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <body>
</html> --}}

