# Generated by Django 4.2.4 on 2023-09-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='color_code',
            field=models.CharField(max_length=7),
        ),
    ]
