# Generated by Django 4.2.4 on 2023-10-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_alter_program_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='program_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
