# Generated by Django 4.2.6 on 2023-10-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0003_alter_programs_program_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='color_code',
        ),
    ]
