# Generated by Django 5.0.1 on 2024-05-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0003_alter_programs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='abbreviation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='programs',
            name='program_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
