# Generated by Django 4.2.4 on 2023-12-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_alter_programs_created_by'),
        ('Accreditation', '0006_area_instrument_instrument_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='program',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Programs.programs'),
            preserve_default=False,
        ),
    ]
