# Generated by Django 4.2.4 on 2023-12-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_alter_programs_created_by'),
        ('Accreditation', '0007_instrument_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='accredbodies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accredbodies_instrument', to='Accreditation.accredbodies'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs_instrument', to='Programs.programs'),
        ),
        migrations.AlterField(
            model_name='instrument_level',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument_level',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_instrument_level', to='Accreditation.instrument'),
        ),
        migrations.AlterField(
            model_name='instrument_level',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_instrument_level', to='Accreditation.accredlevel'),
        ),
        migrations.AlterUniqueTogether(
            name='instrument_level',
            unique_together={('instrument', 'level')},
        ),
    ]
