# Generated by Django 4.2.4 on 2023-12-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0009_remove_area_name_instrument_level_area_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accredlevel',
            name='description',
        ),
        migrations.AlterField(
            model_name='area',
            name='area_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
