# Generated by Django 4.2.4 on 2023-12-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_alter_programs_created_by'),
        ('Accreditation', '0010_remove_accredlevel_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('accredbodies', 'program')},
        ),
    ]
