# Generated by Django 4.2.4 on 2024-01-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0011_alter_instrument_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument_level_area',
            name='name',
        ),
    ]
