# Generated by Django 4.2.4 on 2024-01-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0012_remove_instrument_level_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument_level_area',
            name='label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
