# Generated by Django 4.2.4 on 2024-01-08 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accreditation', '0014_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='level_area_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_level_area_parameter', to=settings.AUTH_USER_MODEL)),
                ('instrument_level_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accreditation.instrument_level_area')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_level_area_parameter', to=settings.AUTH_USER_MODEL)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accreditation.parameter')),
            ],
            options={
                'unique_together': {('parameter', 'instrument_level_area')},
            },
        ),
    ]
