# Generated by Django 4.2.4 on 2024-01-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0020_parameter_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter_indicators',
            name='sub_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_indicators', to='Accreditation.parameter_indicators'),
        ),
    ]
