# Generated by Django 4.2.4 on 2024-01-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0022_components_parameter_component_indicators_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter_components',
            unique_together={('component', 'area_parameter')},
        ),
    ]
