# Generated by Django 4.2.4 on 2024-01-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0023_alter_parameter_components_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter_component_indicators',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
    ]
