# Generated by Django 4.2.4 on 2024-01-21 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accreditation', '0026_rename_tite_component_upload_bin_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='component_upload_bin',
            name='accepted_file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='component_upload_bin',
            name='filename_format',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='uploaded_evidences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='uploaded-evidences/')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_upload_evidences', to=settings.AUTH_USER_MODEL)),
                ('upload_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accreditation.component_upload_bin')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_upload_evidences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
