# Generated by Django 4.2.4 on 2024-01-21 20:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0027_component_upload_bin_accepted_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component_upload_bin',
            name='filename_format',
        ),
        migrations.AddField(
            model_name='component_upload_bin',
            name='accepted_file_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component_upload_bin',
            name='accepted_file_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component_upload_bin',
            name='accepted_file_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
    ]
