# Generated by Django 4.2.4 on 2024-01-21 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0028_remove_component_upload_bin_filename_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_upload_bin',
            name='accepted_file_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
