# Generated by Django 4.2.4 on 2024-01-21 20:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0029_alter_component_upload_bin_accepted_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_upload_bin',
            name='accepted_file_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
    ]
