# Generated by Django 4.2.4 on 2024-01-22 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0003_alter_programs_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accreditation', '0031_alter_component_upload_bin_accepted_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='program_accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('suervey_visit_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_program_accreditation', to=settings.AUTH_USER_MODEL)),
                ('instrument_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accreditation.instrument_level')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_program_accreditation', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Programs.programs')),
            ],
        ),
    ]
