# Generated by Django 4.2.4 on 2024-01-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0032_program_accreditation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program_accreditation',
            old_name='suervey_visit_date',
            new_name='survey_visit_date',
        ),
    ]
