# Generated by Django 4.2.4 on 2024-01-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0003_alter_programs_description'),
        ('Accreditation', '0033_rename_suervey_visit_date_program_accreditation_survey_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_accreditation',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='program_accreditation',
            unique_together={('program', 'instrument_level')},
        ),
    ]
