# Generated by Django 4.2.4 on 2024-01-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0034_program_accreditation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_area_parameter',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parameter_components',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
