# Generated by Django 4.2.4 on 2024-01-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0035_level_area_parameter_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_accreditation',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
