# Generated by Django 4.2.4 on 2024-01-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0037_remove_program_accreditation_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaded_evidences',
            name='file_type',
        ),
        migrations.AddField(
            model_name='uploaded_evidences',
            name='files',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accreditation_records',
            name='accreditation_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_accreditation_level', to='Accreditation.accredlevel'),
        ),
        migrations.AlterField(
            model_name='accreditation_records',
            name='accredited_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accredited_program', to='Accreditation.program_accreditation'),
        ),
    ]
