# Generated by Django 4.2.4 on 2024-01-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0038_remove_uploaded_evidences_file_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaded_evidences',
            old_name='files',
            new_name='file_type',
        ),
    ]
