# Generated by Django 4.2.4 on 2024-01-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0039_rename_files_uploaded_evidences_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_upload_bin',
            name='accepted_file_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
