# Generated by Django 4.2.4 on 2024-01-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0040_alter_component_upload_bin_accepted_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaded_evidences',
            name='file_type',
        ),
    ]
