# Generated by Django 5.0.1 on 2024-01-27 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0041_remove_uploaded_evidences_file_type'),
        ('Programs', '0003_alter_programs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_accreditation',
            name='instrument_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_level_relation', to='Accreditation.instrument_level'),
        ),
        migrations.AlterField(
            model_name='program_accreditation',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_relation', to='Programs.programs'),
        ),
    ]
