# Generated by Django 5.0.1 on 2024-01-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0042_alter_program_accreditation_instrument_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_upload_bin',
            name='accepted_file_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
