# Generated by Django 5.0.1 on 2024-02-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0043_alter_component_upload_bin_accepted_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_accreditation',
            name='due_date',
        ),
        migrations.AddField(
            model_name='instrument_level_area',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
