# Generated by Django 5.0.1 on 2024-02-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0044_remove_program_accreditation_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level_area_parameter',
            name='status',
        ),
        migrations.RemoveField(
            model_name='parameter_components',
            name='status',
        ),
        migrations.AddField(
            model_name='instrument_level',
            name='progress',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument_level_area',
            name='progress',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level_area_parameter',
            name='progress',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter_components',
            name='progress',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
