# Generated by Django 5.0.1 on 2024-02-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0045_remove_level_area_parameter_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument_level',
            old_name='progress',
            new_name='progress_percentage',
        ),
        migrations.RenameField(
            model_name='instrument_level_area',
            old_name='progress',
            new_name='progress_percentage',
        ),
        migrations.RenameField(
            model_name='level_area_parameter',
            old_name='progress',
            new_name='progress_percentage',
        ),
        migrations.RenameField(
            model_name='parameter_components',
            old_name='progress',
            new_name='progress_percentage_percentage',
        ),
    ]
