# Generated by Django 5.0.1 on 2024-02-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0046_rename_progress_instrument_level_progress_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter_components',
            old_name='progress_percentage_percentage',
            new_name='progress_percentage',
        ),
    ]
