# Generated by Django 5.0.1 on 2024-02-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0047_rename_progress_percentage_percentage_parameter_components_progress_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_accreditation',
            name='status',
        ),
        migrations.AddField(
            model_name='program_accreditation',
            name='progress_percentage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
