# Generated by Django 5.0.1 on 2024-02-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0049_remove_program_accreditation_progress_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument_level',
            name='progress_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument_level_area',
            name='progress_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='level_area_parameter',
            name='progress_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter_components',
            name='progress_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
