# Generated by Django 5.0.1 on 2024-02-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0052_user_assigned_to_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_accreditation',
            name='mock_accred_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
