# Generated by Django 5.0.1 on 2024-02-20 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0055_usergroupview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_assigned_to_area',
            old_name='is_chairperson',
            new_name='is_chairman',
        ),
        migrations.AddField(
            model_name='user_assigned_to_area',
            name='is_cochairman',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='user_assigned_to_area',
            unique_together={('assigned_user', 'area')},
        ),
    ]
