# Generated by Django 5.0.1 on 2024-02-21 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0056_rename_is_chairperson_user_assigned_to_area_is_chairman_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_assigned_to_area',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_area', to='Accreditation.instrument_level_area'),
        ),
        migrations.AlterField(
            model_name='user_assigned_to_area',
            name='assigned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
