# Generated by Django 5.0.1 on 2024-02-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0057_alter_user_assigned_to_area_area_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_assigned_to_area',
            unique_together=set(),
        ),
    ]
