# Generated by Django 5.0.1 on 2024-02-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0059_alter_user_assigned_to_area_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_accreditation',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program_accreditation',
            name='result_remarks',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='program_accreditation',
            name='revisit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program_accreditation',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='program_accreditation',
            name='validity_date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program_accreditation',
            name='validity_date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='accreditation_records',
        ),
    ]
