# Generated by Django 5.0.1 on 2024-02-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0060_program_accreditation_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_accreditation',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
