# Generated by Django 5.0.1 on 2024-02-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0061_program_accreditation_is_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_accreditation',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
