# Generated by Django 5.0.1 on 2024-02-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0062_program_accreditation_is_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation_certificates',
            name='certificate_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='accreditation_certificates',
            name='certificate_path',
            field=models.FileField(max_length=300, upload_to='accreditation-certifacates/'),
        ),
    ]
