# Generated by Django 5.0.1 on 2024-02-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0063_alter_accreditation_certificates_certificate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_accreditation',
            name='is_visited',
        ),
    ]
