# Generated by Django 5.0.1 on 2024-02-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0064_remove_program_accreditation_is_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_accreditation',
            name='is_revisited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program_accreditation',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
