# Generated by Django 5.0.1 on 2024-02-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0065_program_accreditation_is_revisited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_accreditation',
            name='is_revisited',
        ),
        migrations.RemoveField(
            model_name='program_accreditation',
            name='is_visited',
        ),
    ]
