# Generated by Django 5.0.1 on 2024-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0070_remove_program_accreditation_result_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_accreditation',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
