# Generated by Django 5.0.1 on 2024-03-24 03:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0071_alter_program_accreditation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accredtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='accredtype',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='area',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='area',
            name='modified_by',
        ),
        # migrations.RemoveField(
        #     model_name='instrument_level_area',
        #     name='area',
        # ),
        migrations.RemoveField(
            model_name='component_upload_bin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='component_upload_bin',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='component_upload_bin',
            name='parameter_component',
        ),
        migrations.RemoveField(
            model_name='component_upload_bin',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='uploaded_evidences',
            name='upload_bin',
        ),
        migrations.AlterUniqueTogether(
            name='instrument_level_area',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='instrument_level_area',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='instrument_level_area',
            name='instrument_level',
        ),
        migrations.RemoveField(
            model_name='instrument_level_area',
            name='modified_by',
        ),
        # migrations.RemoveField(
        #     model_name='user_assigned_to_area',
        #     name='area',
        # ),
        # migrations.RemoveField(
        #     model_name='level_area_parameter',
        #     name='instrument_level_area',
        # ),
        migrations.AlterUniqueTogether(
            name='level_area_parameter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='level_area_parameter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='level_area_parameter',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='level_area_parameter',
            name='parameter',
        ),
        # migrations.RemoveField(
        #     model_name='parameter_components',
        #     name='area_parameter',
        # ),
        migrations.RemoveField(
            model_name='parameter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='modified_by',
        ),
        migrations.AlterUniqueTogether(
            name='parameter_components',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='parameter_components',
            name='component',
        ),
        migrations.RemoveField(
            model_name='parameter_components',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='parameter_components',
            name='modified_by',
        ),
        migrations.AlterUniqueTogether(
            name='program_accreditation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='program_accreditation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='program_accreditation',
            name='instrument_level',
        ),
        migrations.RemoveField(
            model_name='program_accreditation',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='program_accreditation',
            name='program',
        ),
        migrations.RemoveField(
            model_name='result_remarks',
            name='accredited_program',
        ),
        migrations.RemoveField(
            model_name='result_remarks',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='result_remarks',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='uploaded_evidences',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='uploaded_evidences',
            name='uploaded_by',
        ),
        migrations.AlterUniqueTogether(
            name='user_assigned_to_area',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='user_assigned_to_area',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='user_assigned_to_area',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='user_assigned_to_area',
            name='modified_by',
        ),
        migrations.CreateModel(
            name='instrument_level_directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_instrument_level_directory', to=settings.AUTH_USER_MODEL)),
                ('instrument_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accreditation.instrument_level')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_instrument_level_directory', to=settings.AUTH_USER_MODEL)),
                ('parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_directory', to='Accreditation.instrument_level_directory')),
            ],
            options={
                'unique_together': {('name', 'parent_directory', 'instrument_level')},
            },
        ),
        migrations.DeleteModel(
            name='accreditation_certificates',
        ),
        migrations.DeleteModel(
            name='accredtype',
        ),
        migrations.DeleteModel(
            name='area',
        ),
        migrations.DeleteModel(
            name='component_upload_bin',
        ),
        migrations.DeleteModel(
            name='instrument_level_area',
        ),
        migrations.DeleteModel(
            name='level_area_parameter',
        ),
        migrations.DeleteModel(
            name='parameter',
        ),
        migrations.DeleteModel(
            name='parameter_components',
        ),
        migrations.DeleteModel(
            name='program_accreditation',
        ),
        migrations.DeleteModel(
            name='result_remarks',
        ),
        migrations.DeleteModel(
            name='uploaded_evidences',
        ),
        migrations.DeleteModel(
            name='user_assigned_to_area',
        ),
    ]
