# Generated by Django 5.0.1 on 2024-03-24 05:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0072_remove_accredtype_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='instrument_level_directory',
            new_name='instrument_level_folder',
        ),
    ]
