# Generated by Django 5.0.1 on 2024-03-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0073_rename_instrument_level_directory_instrument_level_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument_level_folder',
            name='label',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
