# Generated by Django 5.0.1 on 2024-03-24 13:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0074_instrument_level_folder_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='submission_bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('accepted_file_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('accepted_file_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('accepted_file_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=2000, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_submission_bin', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_submission_bin', to=settings.AUTH_USER_MODEL)),
                ('parent_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accreditation.instrument_level_folder')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_submission_bin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='uploaded-files/')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_upload_files', to=settings.AUTH_USER_MODEL)),
                ('parent_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accreditation.instrument_level_folder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_upload_files', to=settings.AUTH_USER_MODEL)),
                ('upload_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accreditation.submission_bin')),
            ],
        ),
    ]
