# Generated by Django 5.0.1 on 2024-03-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0075_submission_bin_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument_level_folder',
            name='has_assign_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument_level_folder',
            name='has_progress_bar',
            field=models.BooleanField(default=False),
        ),
    ]
