# Generated by Django 5.0.1 on 2024-03-27 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0077_alter_instrument_level_folder_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='upload_bin',
        ),
        migrations.AddField(
            model_name='instrument_level_folder',
            name='accepted_file_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument_level_folder',
            name='accepted_file_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument_level_folder',
            name='accepted_file_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='instrument_level_folder',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument_level_folder',
            name='is_submission_bin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument_level_folder',
            name='remarks',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='instrument_level_folder',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument_level_folder',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_submission_bin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instrument_level_folder',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='submission_bin',
        ),
    ]
