# Generated by Django 5.0.1 on 2024-03-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0078_remove_files_upload_bin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='size_in_mb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
