# Generated by Django 5.0.1 on 2024-03-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0079_files_size_in_mb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='size_in_mb',
        ),
    ]
