# Generated by Django 5.0.1 on 2024-03-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0082_program_accreditation_accreditation_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument_level_folder',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
