# Generated by Django 5.0.1 on 2024-03-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0083_instrument_level_folder_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument_level_folder',
            name='can_be_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
