# Generated by Django 5.0.1 on 2024-04-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0086_usernotassignedview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument_level_folder',
            name='instrument_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_level_folder_relation', to='Accreditation.instrument_level'),
        ),
        migrations.AlterModelTable(
            name='usernotassignedview',
            table='user_group_view',
        ),
        migrations.DeleteModel(
            name='components',
        ),
    ]
