# Generated by Django 5.0.1 on 2024-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0088_files_remarks_files_reviewed_at_files_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument_level_folder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
