# Generated by Django 5.0.1 on 2024-04-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0089_alter_instrument_level_folder_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='can_be_reviewed',
            field=models.BooleanField(default=True),
        ),
    ]
