# Generated by Django 5.0.1 on 2024-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0090_files_can_be_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
