# Generated by Django 5.0.1 on 2024-05-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0091_alter_files_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accredbodies',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accreditation_certificates',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result_remarks',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
