# Generated by Django 5.0.1 on 2024-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0092_alter_accredbodies_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_accreditation',
            name='revisit_compliance_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
