# Generated by Django 5.0.1 on 2024-05-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0093_program_accreditation_revisit_compliance_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation_certificates',
            name='certificate_path',
            field=models.FileField(max_length=300, upload_to='accreditation-certificates/'),
        ),
    ]
