# Generated by Django 5.0.1 on 2024-05-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0094_alter_accreditation_certificates_certificate_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument_level_folder',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
