# Generated by Django 5.0.1 on 2024-05-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0095_instrument_level_folder_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument_level_folder',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
