# Generated by Django 5.0.1 on 2024-05-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0096_instrument_level_folder_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
