# Generated by Django 5.0.1 on 2024-05-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0098_alter_files_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument_level',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='instrument_level',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
