# Generated by Django 5.0.1 on 2024-05-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accreditation', '0099_instrument_level_rating_instrument_level_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='instrument_level_folder',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
